# Generated by Django 4.1.3 on 2022-11-15 23:04

from django.db import migrations, models

room_number = models.IntegerField()
room_type = models.CharField(max_length=100)
floor = models.IntegerField()


def load_initial_data(apps, schema_editor):
    # get our model
    # get_model(appname, modelname)
    room_model = apps.get_model('reservations', 'Room')
    room_model.objects.create (
        room_number=1, room_type="Single", floor=1
        )
    room_model.objects.create(
        room_number=2, room_type="Double", floor=1
    )
    room_model.objects.create(
        room_number=3, room_type="Triple", floor=2
    )
    room_model.objects.create(
        room_number=4, room_type="Quad", floor=2
    )
    room_model.objects.create(
        room_number=5, room_type="King", floor=2
    )

class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),

    ]
